Week 10 Challenge
Task 1: Brent Oil Price Analysis
1. Import Libraries

In [3]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats

from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

plt.style.use("ggplot")

print("Libraries imported successfully.")

Libraries imported successfully.

2. Load the Dataset

In [4]:
# Load Brent Oil Prices dataset

df = pd.read_csv("../data/raw/BrentOilPrices.csv")

df.head()

        Date  Price
0  20-May-87  18.63
1  21-May-87  18.45
2  22-May-87  18.55
3  25-May-87  18.60
4  26-May-87  18.63

In [5]:
# Display dataset shape

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.info()

Rows: 9011
Columns: 2
<class 'pandas.DataFrame'>
RangeIndex: 9011 entries, 0 to 9010
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    9011 non-null   str
 1   Price   9011 non-null   float64
dtypes: float64(1), str(1)
memory usage: 140.9 KB

3. Data Cleaning

In [6]:
# Convert Date column

df["Date"] = pd.to_datetime(df["Date"])

# Sort data

df = df.sort_values("Date")

# Reset index

df.reset_index(drop=True, inplace=True)

df.head()

        Date  Price
0 1987-05-20  18.63
1 1987-05-21  18.45
2 1987-05-22  18.55
3 1987-05-25  18.60
4 1987-05-26  18.63

In [7]:
# Missing values

df.isnull().sum()

Date     0
Price    0
dtype: int64

In [9]:
# Check duplicates

df.duplicated().sum()

np.int64(0)

In [10]:
# Summary statistics

df.describe()

                             Date        Price
count                        9011  9011.000000
mean   2005-02-10 23:46:53.760958    48.420782
min           1987-05-20 00:00:00     9.100000
25%           1996-03-20 12:00:00    19.050000
50%           2005-02-02 00:00:00    38.570000
75%           2014-01-09 12:00:00    70.090000
max           2022-11-14 00:00:00   143.950000
std                           NaN    32.860110