Task 2
Bayesian Change Point Detection
1. Import Libraries

In [1]:

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import pymc as pm
import arviz as az

from scipy import stats

WARNING (pytensor.configdefaults): g++ not available, if using conda: `conda install gxx`
WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.

2. Load Dataset

In [3]:
df = pd.read_csv("../data/raw/BrentOilPrices.csv")

df.head()

        Date  Price
0  20-May-87  18.63
1  21-May-87  18.45
2  22-May-87  18.55
3  25-May-87  18.60
4  26-May-87  18.63

3. Prepare Data

In [4]:
df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values("Date")

df.reset_index(drop=True, inplace=True)

df.head()

        Date  Price
0 1987-05-20  18.63
1 1987-05-21  18.45
2 1987-05-22  18.55
3 1987-05-25  18.60
4 1987-05-26  18.63

In [5]:
#Check
df.info()

df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 9011 entries, 0 to 9010
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    9011 non-null   datetime64[us]
 1   Price   9011 non-null   float64
dtypes: datetime64[us](1), float64(1)
memory usage: 140.9 KB

                             Date        Price
count                        9011  9011.000000
mean   2005-02-10 23:46:53.760958    48.420782
min           1987-05-20 00:00:00     9.100000
25%           1996-03-20 12:00:00    19.050000
50%           2005-02-02 00:00:00    38.570000
75%           2014-01-09 12:00:00    70.090000
max           2022-11-14 00:00:00   143.950000
std                           NaN    32.860110